---
# New Relic license key, used as a bearer token by Prometheus remote_write - confirmed
# via New Relic's own docs this is `authorization: credentials:` (bearer), not a
# custom header. Must live in the SAME namespace as the Prometheus instance that
# references it (openshift-user-workload-monitoring for UWM Prometheus).
#
# Must be an "Ingest - License" type API key from New Relic, not a User key.
# Get it from: New Relic -> (account) -> API keys -> Ingest - License.
#
# Fill in <new-relic-license-key> below, then:
#   oc apply -f 03-newrelic-remote-write-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-remote-write-creds
  namespace: openshift-user-workload-monitoring
type: Opaque
stringData:
  token: "<new-relic-license-key>"
